undefined reference to flushline issue resolved
added flushline definition to touchgfx-->target-->generated>STM32DMA.cpp to resolve the issue.

issue raised due to touchgfx files generated with the old version.